# Required environment variables: UID, TZ
#
# Environment variable UID is used for the container's user's UID.
# If missing or empty, Dockerfile uses a default (probably 1000).
# This is to let access the container to the host's volume ./volumes/.
# Note that bash's UID is not exported. So you may build with
#
# (export UID && docker compose build)
services:
  controller:
    build:
      context: build
      args:
        - UID
    image: js7
    container_name: js7-controller
    hostname: js7-controller
    command: [
      "js7-controller",
      "--arg0=js7-controller",
      "-J-Xmx200m",
      "--processor-limit=1/4"
    ]
    #networks:
    #  - default
    ports:
      - "127.0.0.1:4443:4443"
      - "127.0.0.1:4444:4444"
    #cpus: 16
    working_dir: /home/js7
    environment:
      - TZ=${TZ-}
    volumes:
      - ./volumes/controller/config:/var/opt/js7/controller/config:ro
      - ./volumes/controller/data/cache:/var/opt/js7/controller/data/cache:delegated
      - ./volumes/controller/data/logs:/var/opt/js7/controller/data/logs:delegated
      - ./volumes/controller/data/state:/var/opt/js7/controller/data/state:delegated
    stop_grace_period: 15s
    restart: unless-stopped

  backup-controller:
    build:
      context: build
      args:
        - UID
    image: js7
    container_name: js7-backup-controller
    hostname: js7-backup-controller
    command: [
      "js7-controller",
      "--arg0=js7-backup-controller",
      "-J-Xmx200m",
      "--processor-limit=1/8"
    ]
    #cpus: 8
    #networks:
    #  - default
    #ports:
    #Does not work for Docker 2.2.3.0 macOS:  - "127.0.0.2:4444:4444"
    working_dir: /home/js7
    environment:
      - TZ=${TZ-}
    volumes:
      - ./volumes/backup-controller/config:/var/opt/js7/controller/config:ro
      - ./volumes/backup-controller/data/cache:/var/opt/js7/controller/data/cache:delegated
      - ./volumes/backup-controller/data/logs:/var/opt/js7/controller/data/logs:delegated
      - ./volumes/backup-controller/data/state:/var/opt/js7/controller/data/state:delegated
    stop_grace_period: 15s
    restart: unless-stopped

  subagent-1a:
    image: js7
    container_name: js7-subagent-1a
    hostname: js7-subagent-1a
    command: [
      "js7-subagent",
      "--arg0=js7-subagent-1a",
      "-J-Xmx200m",
      "--processor-limit=1/4"
    ]
    #cpus: 14
    working_dir: /home/js7
    environment:
      - TZ=${TZ-}
    volumes:
      - ./volumes/subagent-1a/config:/var/opt/js7/agent/config:ro
      - ./volumes/subagent-1a/data/cache:/var/opt/js7/agent/data/cache:delegated
      - ./volumes/subagent-1a/data/logs:/var/opt/js7/agent/data/logs:delegated
      - ./volumes/subagent-1a/data/state:/var/opt/js7/agent/data/state:delegated
      - ./volumes/subagent-1a/data/work:/var/opt/js7/agent/data/work:delegated
    stop_grace_period: 15s
    restart: unless-stopped

  subagent-1b:
    image: js7
    container_name: js7-subagent-1b
    hostname: js7-subagent-1b
    command: [
      "js7-subagent",
      "--arg0=js7-subagent-1b",
      "-J-Xmx200m",
      "--processor-limit=1/4"
    ]
    #cpus: 8
    working_dir: /home/js7
    environment:
      - TZ=${TZ-}
    volumes:
      - ./volumes/subagent-1b/config:/var/opt/js7/agent/config:ro
      - ./volumes/subagent-1b/data/cache:/var/opt/js7/agent/data/cache:delegated
      - ./volumes/subagent-1b/data/logs:/var/opt/js7/agent/data/logs:delegated
      - ./volumes/subagent-1b/data/state:/var/opt/js7/agent/data/state:delegated
      - ./volumes/subagent-1b/data/work:/var/opt/js7/agent/data/work:delegated
    stop_grace_period: 15s
    restart: unless-stopped

  subagent-1c:
    image: js7
    container_name: js7-subagent-1c
    hostname: js7-subagent-1c
    command: [
      "js7-subagent",
      "--arg0=js7-subagent-1c",
      "-J-Xmx200m",
      "--processor-limit=1/8"
    ]
    #cpus: 4
    working_dir: /home/js7
    environment:
      - TZ=${TZ-}
    volumes:
      - ./volumes/subagent-1c/config:/var/opt/js7/agent/config:ro
      - ./volumes/subagent-1c/data/cache:/var/opt/js7/agent/data/cache:delegated
      - ./volumes/subagent-1c/data/logs:/var/opt/js7/agent/data/logs:delegated
      - ./volumes/subagent-1c/data/state:/var/opt/js7/agent/data/state:delegated
      - ./volumes/subagent-1c/data/work:/var/opt/js7/agent/data/work:delegated
    stop_grace_period: 15s
    restart: unless-stopped

  subagent-2a:
    image: js7
    container_name: js7-subagent-2a
    hostname: js7-subagent-2a
    command: [
      "js7-subagent",
      "--arg0=js7-subagent-2a",
      "-J-Xmx200m",
      "--processor-limit=1/8"
    ]
    #cpus: 7
    working_dir: /home/js7
    environment:
      - TZ=${TZ-}
    volumes:
      - ./volumes/subagent-2a/config:/var/opt/js7/agent/config:ro
      - ./volumes/subagent-2a/data/cache:/var/opt/js7/agent/data/cache:delegated
      - ./volumes/subagent-2a/data/logs:/var/opt/js7/agent/data/logs:delegated
      - ./volumes/subagent-2a/data/state:/var/opt/js7/agent/data/state:delegated
      - ./volumes/subagent-2a/data/work:/var/opt/js7/agent/data/work:delegated
    stop_grace_period: 15s
    restart: unless-stopped

  cluster-watch:
    image: js7
    container_name: js7-cluster-watch
    hostname: js7-cluster-watch
    command: [
      "js7-cluster-watch",
      "--arg0=js7-cluster-watch",
      "-J-Xmx50m",
      "--processor-limit=1",
      "--cluster-watch-id=CLUSTER-WATCH",
      "--cluster-node-uri=https://js7-controller:4443",
      "--cluster-node-uri=https://js7-backup-controller:4443"
    ]
    #cpus: 0.5
    working_dir: /home/js7
    environment:
      - TZ=${TZ-}
    volumes:
      - ./volumes/cluster-watch/config:/var/opt/js7/cluster-watch/config:ro
      - ./volumes/cluster-watch/data/cache:/var/opt/js7/cluster-watch/data/cache:delegated
      - ./volumes/cluster-watch/data/logs:/var/opt/js7/cluster-watch/data/logs:delegated
      - ./volumes/cluster-watch/data/state:/var/opt/js7/cluster-watch/data/state:delegated
    stop_grace_period: 15s
    restart: unless-stopped

  cluster-watch-b:
    image: js7
    container_name: js7-cluster-watch-b
    hostname: js7-cluster-watch-b
    command: [
      "js7-cluster-watch",
      "--arg0=js7-cluster-watch-b",
      "-J-Xmx50m",
      "--processor-limit=1",
      "--cluster-watch-id=CLUSTER-WATCH-B",
      "--cluster-node-uri=https://js7-controller:4443",
      "--cluster-node-uri=https://js7-backup-controller:4443"
    ]
    #cpus: 0.5
    working_dir: /home/js7
    environment:
      - TZ=${TZ-}
    volumes:
      - ./volumes/cluster-watch-b/config:/var/opt/js7/cluster-watch/config:ro
      - ./volumes/cluster-watch-b/data/cache:/var/opt/js7/cluster-watch/data/cache:delegated
      - ./volumes/cluster-watch-b/data/logs:/var/opt/js7/cluster-watch/data/logs:delegated
      - ./volumes/cluster-watch-b/data/state:/var/opt/js7/cluster-watch/data/state:delegated
    stop_grace_period: 15s
    restart: unless-stopped
    depends_on:
      - cluster-watch # Delay start of this cluster-watch-b and give way to the other cluster-watch
    profiles:
      - dontStart # Non-existent profile

  provider:
    image: js7
    container_name: js7-provider
    hostname: js7-provider
    command: [
      "js7-provider",
      "--arg0=js7-provider",
      "-J-Xmx100m",
      "--processor-limit=1",
      "--controller-uri=https://js7-controller:4443"
    ]
    #cpus: 0.5
    working_dir: /home/js7
    environment:
      - TZ=${TZ-}
    volumes:
      - ./volumes/provider/config:/var/opt/js7/provider/config:ro
      - ./volumes/provider/data/cache:/var/opt/js7/provider/data/cache:delegated
      - ./volumes/provider/data/logs:/var/opt/js7/provider/data/logs:delegated
      - ./volumes/provider/data/state:/var/opt/js7/provider/data/state:delegated
    restart: unless-stopped

  proxy:
    image: js7
    container_name: js7-proxy
    hostname: js7-proxy
    command: [
      "js7-proxy",
      "--arg0=js7-proxy",
      "-J-Xmx200m",
      "--processor-limit=1",
      #"--cluster-watch-id=PROXY",
      "--cluster-node-uri=https://js7-controller:4443",
      "--cluster-node-uri=https://js7-backup-controller:4443" ]
    #cpus: 2
    working_dir: /home/js7
    environment:
      - TZ=${TZ-}
    volumes:
      - ./volumes/proxy/config:/var/opt/js7/proxy/config:ro
      - ./volumes/proxy/data/cache:/var/opt/js7/proxy/data/cache:delegated
      - ./volumes/proxy/data/logs:/var/opt/js7/proxy/data/logs:delegated
      - ./volumes/proxy/data/state:/var/opt/js7/proxy/data/state:delegated
    restart: unless-stopped
    stop_grace_period: 15s

  proxy-b:
    image: js7
    container_name: js7-proxy-b
    hostname: js7-proxy-b
    command: [
      "js7-proxy",
      "--arg0=js7-proxy-b",
      "-J-Xmx200m",
      "--processor-limit=1",
      #"--cluster-watch-id=PROXY-B",
      "--cluster-node-uri=https://js7-controller:4443",
      "--cluster-node-uri=https://js7-backup-controller:4443" ]
    #cpus: 1
    working_dir: /home/js7
    environment:
      - TZ=${TZ-}
    volumes:
      - ./volumes/proxy-b/config:/var/opt/js7/proxy/config:ro
      - ./volumes/proxy-b/data/cache:/var/opt/js7/proxy/data/cache:delegated
      - ./volumes/proxy-b/data/logs:/var/opt/js7/proxy/data/logs:delegated
      - ./volumes/proxy-b/data/state:/var/opt/js7/proxy/data/state:delegated
    restart: unless-stopped
    stop_grace_period: 15s
    depends_on:
      - proxy # Delay start of this proxy-b and give way to the other proxy
    profiles:
      - dontStart # Non-existent profile

networks:
  default:
    name: js7
